UN-OCHA/reports-site

- .env
- .gitignore
- Dockerfile
- README.md
- docker-compose.yml
- nuxt.config.js
- package-lock.json
- package.json
- run_node
> [OPS-4931] Prep for prod use.

- components/AppBar.vue
- components/AppFooter.vue
- components/AppHeader.vue
- components/Articles.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- package-lock.json
- pages/country/_slug.vue
- static/global.css
> DSR-7: Key Figures

- components/AppFooter.vue
- components/AppHeader.vue
- components/KeyFigures.vue
- pages/country/_slug.vue
- pages/index.vue
- static/global.css
I ignored IE11 while beginning to hack on this app but with an official dev URL I don't want egg on my face. Only on my code.
Site is decent in IE9+ even though our minimum target browser is IE11. It still works just fine in all the evergreens.
> DSR-20: IE11 cleanup

- components/Articles.vue
- components/KeyMessages.vue
- nuxt.config.js
- static/global.css
Initial PR to get Article images working. Currently the PR doesn't address the "read more" functionality.
> DSR-9: Narratives

- components/KeyFigures.vue
- components/KeyMessages.vue
- pages/country/_slug.vue
Did some minor visual styling based on the live prototype fun we had during the demo yesterday. Some other changes on the Contentful side to restrict the key messages and I believe this is good to go for now.
> DSR-6: Key Messages

- nuxt.config.js
me not good at server :trollface:
> DSR-19: Properly connect the .env vars to client-side Vue

- static/global.css
> DSR-17: apply Roboto to entire document

- components/Articles.vue
Fixed the "read-more" treatment of long articles so that it only shows up on interactive `screen` media instead of `print`.
> DSR-27: read-more link should only appear on screen media

- components/AppFooter.vue
- components/AppHeader.vue
- pages/country/_slug.vue
- pages/index.vue
Minimal update to frontpage just to get the convo started. Another round will come once we've got a temporary design.
> DSR-3: minimal frontpage

- pages/index.vue
Fix the titles to follow branding.
> DSR-3: headings should follow branding

- components/AppHeader.vue
Some preliminary work while we continue setting up Snap Service.
> DSR-46: hide AppHeader when using Snap Service PDF

- _migrations/03-create-mailchimpSignup.js
- components/AppHeader.vue
- pages/country/_slug.vue
Straight link to an arbitrary URL. Managed within Contentful.
> DSR-47: MVP MailChimp integration

- components/AppHeader.vue
Addressing QA for the messed up header. Took a proper pass and tested on mobile this time.
> DSR-48: make it not terrible on mobile

- components/AppHeader.vue
This PR adds email sharing to the social drop-down. Actual text needs to be nailed down but I put something not-embarrassing in case that takes a minute.
> DSR-5: email share link

- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- pages/country/_slug.vue
More bugs smoothed over as a result of recent Snap testing
> Remove extra bottom-border from printed PDFs

- components/CardActions.vue
> DSR-39: connect to Snap Service!

- nuxt.config.js
This might resolve our issue with CTF_ENVIRONMENT not being set in server.
> Use master as default Contentful environment

- components/CardActions.vue
> DSR-39: allow staging to be snapped

- components/AppHeader.vue
- components/Article.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- locales/en.js
- locales/fr.js
- middleware/i18n.js
- nuxt.config.js
- package-lock.json
- package.json
- pages/country/_slug.vue
- plugins/i18n.js
- store/index.js
This PR allows localization of strings in the UI. English used as base lang and when no translation is present for a string, it will display English for that one term.
> DSR-38: French string translations

- locales/en.js
- locales/fr.js
- pages/index.vue
Follow-up to #63 because I'd forgotten about the homepage.
> DSR-38: translate homepage

- components/AppHeader.vue
- components/Article.vue
- components/Cluster.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- components/_Global.vue
- pages/country/_slug.vue
- pages/index.vue
- store/index.js
I finally sorted how to react to changes to the Vuex store. Removed the full-refresh that I was relying on before, and anything that can be translated should auto-update when the language switcher is changes.
I also moved the switcher so it stays in one place on desktop when switching from home to a sitrep.
> DSR-38: better ux for lang switcher

- components/AppFooter.vue
- components/CardFooter.vue
- components/CardHeader.vue
- components/Contacts.vue
This was a cleanup task I wanted to do once I realized you can do type checking on input data passed to components. Everything is declared and if bad data were ever passed in, then the Component will be able to report the reason with a more informative error.
I also noticed I'd overlooked some minor translation and coding standard stuff. It's fixed.
> DSR-56: declare all component proptypes

- components/Article.vue
Still having trouble getting articles with images to truncate correctly.
Fixed another bug with mobile layout read-more expanding too far.
> DSR-71: new method for calculating image heights

- components/Article.vue
Another attempt to get read-more truncation to work with full image height
> DSR-71: wrap Article mounted() event in nextTick

- components/Article.vue
This one's gonna have to live in the backlog for a while. I'm stumped.
Removing the ineffective solution and did minor code standards.
> DSR-71: remove nextTick

- pages/country/_slug.vue
- static/global.css
Tighten up the margins and stuff for DSR content area so it's more dense on the PDF output.
> DSR-83: PDF design tweaks

- pages/country/_slug.vue
Trying to balance the need for fresh content with quick server response, we're generating static files periodically. However it's already caused some concern when updates from Contentful do not apply immediately.
Client-side navigations don't have a problem because they are already using Contentful responses to build the new page of data. But direct views of a URL were revealing the problem.
This PR resolves the issue when directly viewing a URL by forcing an additional client-side request which re-populates the data for the page. There's a slight lag of course, but within a few seconds the changes are reflected. GIF:
> DSR-88: direct visits include client-side API fetches to update stale HTML

- components/Snap.vue
- components/SnapCard.vue
- components/SnapPage.vue
- static/global.css
While doing some other work around Snap I bumped this out of place. I reorganized everything to go in its proper component and pulled the truly global styles out into the right file.
> DSR-89: fix position of app bar button

- components/AppHeader.vue
My original PR #88 wasn't thorough enough. This one (I daresay!) is. I tested with ultra-long-you-cant-believe-its-not-butter titles and made sure to squish the window plenty once I settled on something that looked good.
> DSR-92: share buttons at all screen sizes

- components/AppHeader.vue
- locales/en.js
- locales/fr.js
Keeping up with the spreadsheet.
> French translations

- components/AppBar.vue
- components/AppHeader.vue
- pages/index.vue
I forgot to sort in #100 — sorting both on homepage and in the AppBar now.
I also added clickaway listener so that clicks outside the expanded menu will close the dialog. Primarily for desktop.
> DSR-91: sort SitReps on homepage and AppBar

- nuxt.config.js
- package-lock.json
- package.json
I forgot to point the apple touch icon to the new filename. blah.
> DSR-93: apple-touch-icon points to new filename

- components/CardFooter.vue
- components/CardHeader.vue
- locales/en.js
- locales/fr.js
Global mixin and locale variable for CardHeader subtitle, and CardFooter date
> DSR-108 localized CardHeader and CardFooter

- components/AppHeader.vue
This fixes all the localized strings in the PDF header. I also addressed the `this`-related coding standards while I was in there.
> DSR-122: localize PDF header subtitles

- components/AppHeader.vue
- components/SnapPage.vue
- locales/en.js
- locales/fr.js
- pages/404.vue
- pages/index.vue
I piled a couple unticketed outstanding French translations, consolidation of date formats, the ability to localize PDF footers, and including the URL of the sitrep in the PDF footer all into one crazy PR.
This is how we break stuff!
> Regression Sessions

- components/Snap.vue
- components/SnapCard.vue
- components/SnapPage.vue
Adding the `service` param to help us with ELK mining.
> All Snaps should report the requesting service

- components/Snap.vue
- components/SnapCard.vue
- components/SnapPage.vue
This PR is for @teodorescuserban to merge once the appropriate changes have been made to the stack.
> OPS-5333: i was a bad boy

- components/AppHeader.vue
Miguel got most of the stats under control but asked that I apply some unique classes to the language switcher `<option>` tags. This will help him filter and properly track language switches.
> DSR-120: add unique classes to language selection options for GTM

- _migrations/10-create-interactive.js
- components/Interactive.vue
- components/_Global.vue
- locales/en.js
- locales/fr.js
- pages/country/_slug.vue
This PR opens the way to link to various services that produce interactive graphics. Our requirement was for Tableau and PowerBI but you can link out to anything.
The component also introduces our first responsive image! It's pretty gnarly markup, but I tested it pretty extensively and was happy with the results in Chrome, FF, Edge, and even IE11 when configuring the fallback image for desktop.
> DSR-31: link to external Interactives

- _migrations/10-create-interactive.js
During demo we discussed making both Title and Description optional. So say we all.
> DSR-31: followup to make title optional

- components/SnapPage.vue
- locales/en.js
- locales/fr.js
🎶 the Snaps, they are a-changin' 🎶 
We want to get HR.info on Snap Service, and it required some breaking changes. This PR addresses the updates and also maintains the old behavior. If we deploy this first, we can seamlessly cut over Snap Service without any disruption on DSR site.
> DSR-144: keep up with Snap API

- components/AppBar.vue
One more follow-up. Saw ugly toggle on Snaps coming from Dev. Fixed!
> DSR-154: suppress AppBar toggle on all Snaps

- package-lock.json
- package.json
Bumping major because we're altering the Contentful schema which affects other API consumers.
> Version 2.0.0

- package-lock.json
- package.json
- pages/_lang/country/_slug.vue
Follow-up to multilingual release to make sure our social cards match new URL structure.
> DSR-172: social meta URL fix

- components/AppBar.vue
- components/AppFooter.vue
- components/AppHeader.vue
- components/CardActions.vue
- components/CardFooter.vue
- components/CardHeader.vue
- components/KeyMessages.vue
- components/README.md
- components/SitrepList.vue
- layouts/default.vue
- locales/ar.js
- nuxt.config.js
- pages/404.vue
- pages/_lang/country/_slug.vue
- plugins/i18n.js
- store/index.js
This is my initial effort at Arabic RTL layout.
> DSR-171: RTL layout and Arabic translations

- components/KeyFinancials.vue
Nice and easy. Displays year when we have it, no change when FTS data not available.
> DSR-133: display year of FTS plan

- components/Article.vue
- components/KeyFinancials.vue
- components/SnapCard.vue
- components/SnapPage.vue
- pages/_lang/country/_slug.vue
I just totally blanked on this while doing the other work. Cleans up the PDF to be as spiffy as RTL pages themselves. I'm not sure if I got pagination right but we'll wait for complaints and fix it.
Also snuck in [DSR-145](https://humanitarian.atlassian.net/browse/DSR-145), removed the four old params since we're rendering PDF Header/Footer completely custom now.
> DSR-183: RTL Snap PDF output

- components/Cluster.vue
- components/_Global.vue
- pages/_lang/country/_slug.vue
We wanted to do this before the first cluster gets added. While I was in there bumping things around, I fixed all the outstanding RTL issues on both screen and PNG/PDF.
> DSR-135: integrate clusters into content stream

- assets/Global.scss
- components/KeyFinancials.vue
Make a cute little pie chart out of FTS progress:
> DSR-187: FTS pie chart

- components/AppFooter.vue
- pages/_lang/_slug.vue
Adjusting About page tech section.
> DSR-104: adjust About page

- components/AppHeader.vue
- package-lock.json
- package.json
- pages/_lang/_slug.vue
- pages/_lang/country/_slug.vue
- pages/_lang/index.vue
Remove the old hardcoded system of fallback headings. That was 🤦‍♂️ anyway.
> DSR-104: fix AppHeader for Basic Pages

- locales/ar.js
Got some revisions from our reviewers.
> DSR-171: new Arabic translations

- components/_Page.vue
- pages/_lang/_slug.vue
- pages/_lang/index.vue
Reshuffling some CSS to ensure that it appears on all basic pages. I moved the layout into `Page.vue` and scoped it to a class.
> DSR-195: fix Arabic on IE11 homepage

- _ui/README.md
- _ui/dsrSidebarTextInput.html
- _ui/sitrep.internalReliefWebEmailCc.html
There are no changes to the active codebase in this PR.
Perhaps in the future if we wanted to use the extensions more heavily we will serve them from this GitHub repo, but for now the file is just a copy of the canonical on Contentful.
> DSR-192: RW Email CC field

- pages/404.vue
Restoring page title on 404, but this time it's a meaningful one!
> DSR-199: explicit title for 404 page

- components/SitrepList.vue
- pages/_lang/country/_slug.vue
Leftover from DSR-173. Should have been removed during that branch.
In other news, the linter isn't giving me warnings as I expected. I'll run it manually and throw any fixes in here.
> DSR-208: remove orphaned code

- locales/ar.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
> DSR-212: localize 'Visual' string

- locales/uk.js
I missed a few and I apologize.. 🙈
> DSR-221: update Ukrainian translations

- _stack/DSRWinstonReporter.js
- pages/_lang/country/_slug.vue
Log some more stuff when outputting an error. @teodorescuserban FYI.
> DSR-223: log more details when encountering errors

- _ui/dsrSidebarTextInput.html
- _ui/dsrSidebarTextInputAdminOnly.html
This has no effect on the admin UI. It's simply a record of what we've uploaded to Contentful.
> DSR-220: saving our CTF-hosted UI-Ext to the codebase

- _stack/DSRWinstonReporter.js
- pages/_lang/country/_slug.vue
Trying to standardize format in ELK while avoiding altering what Consola provides as its default.
> DSR-166: log format

- nuxt.config.js
don't want to make beepers beep!
> DSR-227: avoid logging to stdout

- locales/ar.js
Fixing typos in the main headings.
> DSR-229: fix Arabic typo in SitRep title

- .gitignore
- nuxt.config.js
- package-lock.json
- package.json
- yarn.lock
Adding NewRelic monitoring to our app. Per @teodorescuserban he is handling all environment variables within container and all I have to do is include the library.
> OPS-5691: NewRelic server-side monitoring

- package-lock.json
- package.json
- yarn.lock
Our lockfiles are already up to this version, but ¯\\_\(ツ)\_/¯
> DSR-232: ensure a minimum version of webpack-bundle-analyzer

- package-lock.json
- package.json
- yarn.lock
Affected dependencies have an official fix now.
> OPS-5656: update tar for real this time

- _tests/About.test.js
- _tests/AppFooter.test.js
Updating a test that should have been changed during #230 plus adding a few new ones for About page.
> DSR-237: Update E2E

- components/AppFooter.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyMessages.vue
- layouts/error.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
- nuxt.config.js
- pages/_lang/_slug.vue
- pages/_lang/country/_slug.vue
- pages/_lang/index.vue
We had some more mishaps with unpublished content and the logs were devoid of information.  This PR provides the following:
- Better protection against rendering errors for required SitRep elements
- Explicit detection of insufficient SitRep data, throwing errors when it occurs
- A new error page for HTTP 500
- Readjustment of page title logic on all pages to accommodate new error page requirements.
> DSR-238: better data handling and error reporting

- components/AppHeader.vue
Title says it all. Thanks to Jonathan for the tip on search formats.
> DSR-177: shorten RW archive URL format

- README.md
- components/_Global.vue
- package.json
- pages/_lang/country/_slug.vue
- yarn.lock
This PR introduces two things:
- A generic mechanism for using GTM within any Vue component
- An event listener for `window.resize` that sends the new `window.innerWidth` to GA
> DSR-235: track window resize in GTM

- README.md
- pages/_lang/country/_slug.vue
We need to follow the existing casing style for events.
> DSR-235: capitalize GA event labels

- _tests/404.test.js
- layouts/error.vue
Small follow-up to make our tests match up with the codebase.
> DSR-238: E2E follow-up

- pages/_lang/country/_slug.vue
To ensure that we can analyze individual values, we are using the Label field to log the width value.
Third time's a charm?
> DSR-235: reformat event tracking

- components/SnapPage.vue
There used to be DSR-specific code in Snap Service. Not anymore.
> SNAP-54: explicitly set pdfMarginTop param in PDF requests

- components/AppBar.vue
- components/SitrepList.vue
We had an issue with long titles. This PR attempts to make them a little less conspicuous.
> DSR-243: more graceful handling of long titles in AppBar

- components/KeyFinancials.vue
- layouts/error.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
- Updates the strings and translations for Funding box.
- Adds translations for the 500 internal server error page.
> DSR-245: FTS/500 error translations

- components/AppBar.vue
- components/SitrepList.vue
> DSR-243: AppBar RTL followup

- components/AppBar.vue
Fixing a Lighthouse complaint about a11y
> DSR-248: properly encapsulate nested lists

- yarn.lock
I learned about yarn and now can update packages!
> keeping things up to date

- components/Interactive.vue
- components/Video.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
Mimic the way Video handles being printed in a PDF. Translations pending.
> DSR-257: provide plaintext link within PDFs of Interactives

- components/_Page.vue
- layouts/default.vue
- pages/_lang/_slug.vue
I thought doing this was clever. It was a little too clever.
> DSR-259: unflip images on RTL SitReps

- components/Cluster.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
Just waiting for feedback/approval on this one. It can even be deployed without the field existing in Contentful.
> DSR-255: allow Cluster to be labelled Sector

- components/Cluster.vue
I never tested Clusters in RTL. Now I have.
> DSR-262: fix RTL Cluster layouts

- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
Clearing out our spreadsheet and just marking everything as done.
These strings aren't used anywhere yet, but I assembled a table using the Vue translation system to test all of them:
> DSR-269: Add translations for each language in each language

- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
Followup to add translations to relative timestamps.
> DSR-182: translations for relative timestamps

- package.json
need a new version for a release
> DSR-182: version bump

- _tests/AppBar.test.js
- package.json
Fixing E2E for AppBar following the changes in #279
> DSR-268: fix E2E for AppBar

- Dockerfile
- package.json
- run_node
- yarn.lock
Upgrade node.js docker container so we can use newrelic 6.0.0
> OPS-6010: node/newrelic upgrade

- components/SnapCard.vue
- locales/README.md
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/uk.js
- plugins/i18n.js
- store/index.js
Burundi office requested their prevailing local language. It's not complete yet but it's at least a good step towards getting it primed for review with official content.
> DSR-295: local language — Kirundi

- components/AppHeader.vue
- components/SnapCard.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/uk.js
Updated the Kirundi translation file with additions/corrections.
I also converted the old-style tokens to the new format so that it's consistent across all languages and strings.
* Old style: `THING` or `COUNTRY` all caps, **no brackets**
* New style: `[THING]` or `[COUNTRY]` all caps, **with brackets**
> DSR-295: Kirundi round 2

- locales/ar.js
Some changes to Arabic translations. We'll keep trying til we get it right!
> DSR-298: update Arabic translations following feedback from Yemen office

- store/index.js
Using FR as moment.js fallback when active language is Kirundi.
> DSR-295: use French as Kirundi fallback language

- _tests/Card.test.js
- _tests/SitRep.test.js
- pages/_lang/country/_slug/card/_sysid.vue
E2E tests for standalone cards. Already caught bugs writing the tests! 👍 👍 👍
> DSR-277: E2E tests

- _tests/Card.test.js
- _tests/SitRep.test.js
- pages/_lang/country/_slug/card/_sysid.vue
- pages/_lang/country/_slug/index.vue
This PR cleans up how we output base URLs, adds `og:locale`, adds `og:url`, switches `og:type` to `article`
> DSR-305: more meta tag cleanup

- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/so.js
- locales/uk.js
- plugins/i18n.js
- store/index.js
Initial pass at adding Somali language.
> DSR-301: first pass for Somali language

- package.json
- yarn.lock
> DSR-314: update dependencies

- Dockerfile
- nuxt.config.js
- package.json
- yarn.lock
Starting to add some RSS feeds for use by our own internal tools. There's no markup or otherwise a signal on the public site for these feeds.
> DSR-312: RSS feeds Ep 1

- nuxt.config.js
> DSR-312: add country/office name into RSS feed title tag for MailChimp

- components/Article.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/Video.vue
- components/Visual.vue
- nuxt.config.js
- package.json
- yarn.lock
Trying to pass more human-friendly content into MailChimp
> DSR-312: RSS feeds in plain-text

- nuxt.config.js
More human-formatting for MailChimp
> DSR-312: better line-breaks for Highlights in sitreps.xml

- nuxt.config.js
Unescaping the HTML in RSS that we send to MailChimp, because their docs do seem to indicate they'll accept and render it.
> DSR-312: unescape RSS html

- layouts/default.vue
Get that timestamp away from the CardActions buttons.
> DSR-303: adjust layout of Card timestamp on mobile

- package.json
- yarn.lock
Upgrades Contentful Migration to latest version.
> DSR-319: upgrade CTF migration script

- components/SnapPage.vue
- package.json
I forgot to use my 🧠 while building this originally.
> DSR-322: proper use of CSS Grid in PDF Footer

- package.json
I should have done this in the previous release but at least this way we'll bump to the right number next time.
> bump package.json

- components/AppFooter.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/so.js
- locales/uk.js
We need ToS in addition to privacy/copyright links. Points to un.org like the others.
> DSR-326: ToS link in Footer

- pages/_lang/country/_slug/index.vue
add 2020 to our FTS requests. These FTS requests are getting out of hand but this will patch it up for this year.
> DSR-328: slap 2020 into the FTS data array

- components/SnapPage.vue
it's a silly solution but it seems to work pretty well.
> DSR-329: add a small delay to give lazy images time to load

- components/SnapPage.vue
- package.json
it wasn't enough the first time. this will make the UX suffer a tad, but will probably be a decent band-aid.
> DSR-329: crank it up to 2000

- components/SnapPage.vue
- package.json
> Production Release 2020-01-28 THE ACTUAL SEQUEL

- package.json
- yarn.lock
> OPS-6350: update deps

- _migrations/19-update-articleRegional.js
> DSR-335: make sure that SitReps can reference articleRegional

- .gitignore
- .travis.yml
- _tests/unit/_Global.spec.js
- babel.config.js
- jest.config.js
- package.json
- pages/_lang/country/_slug/index.vue
- yarn.lock
We have decided to make Funding optional. All you have to do is leave the two fields blank (FTS URL and manually-entered figures)
There's unit testing now. I originally thought I'd test the Funding box but after doing the setup I realized trying to unit test our SitRep page was going to be too much. At least it's there for a rainy day.
> DSR-336: make funding box optional

- layouts/error.vue
I did this tiny, tiny bugfix while opening the editor for the FTS work which got delayed.
> DSR-340: fix assets on error pages

- pages/_lang/country/_slug/index.vue
FTS is publishing 2021. We can support it now! I took 2018 out of the mix.
> DSR-368: FTS 2021

- Dockerfile
> [OPS-7052] fix dockerfile

- package.json
- yarn.lock
> DSR-370: dependency updates

- package.json
- yarn.lock
Bumping pm2 to latest release.
> OPS-7395: bump pm2

- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/so.js
- locales/uk.js
We had links 404ing and now we won't.
> CD-332: update footer links to match new UN.org URLs

- package.json
- yarn.lock
It behaves exactly like our other node.js projects.
> [DSR-385] install standard-version and configure to skip tags
