- components/AppFooter.vue
- package-lock.json
- package.json
Latest change was to simply use three content-managed links instead of hardcoding a top-level RW link. Now editors can enter any three links they want. They all open in a new tab.
> DSR-10: footer links

- nuxt.config.js
After some discussion we decided it will be better to use a file to store secrets, so that it's available to docker when both building the image and running the container.
@teodorescuserban please give this a look and confirm it's properly implementing what you proposed.
> DSR-19: switch back to contentful JSON tokens

- components/Article.vue
- components/Card.vue
- components/CardActions.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- layouts/default.vue
- package-lock.json
- package.json
- pages/country/_slug.vue
- static/global.css
I did some important but disruptive reorganization when building PNG functionality. It is blocking my progress in other smaller tickets so I'm merging this WIP in order to continue on other tasks. The buttons themselves are visually hidden from view so merging this PR will not create any broken UI elements on the staging site.
- `Articles.vue` -> `Article.vue` (turned its output into a single card, and moved the loop to the page logic where the content is requested)
- Introduced `CardActions.vue` to encapsulate the actions that can be taken on an individual card (Save as PNG, Share, etc)
- sorta-kinda-works with Snap Service (on my local, :trollface:)
> DSR-39: WIP for PNG Snaps

- components/Article.vue
- components/Card.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyMessages.vue
- pages/country/_slug.vue
- static/global.css
After soliciting feedback on yesterday's work, I was pointed to a pre-existing design that I didn't know about. This PR brings us much closer to the design.
- reduced font-size means much more content fits on A4 sheets
- got rid of my thick blue lines in favor of thinner, lighter lines to demarcate cards
- changed content order to place Article images before text. Text flows beneath them on print.
- Figures/Financials use black instead of blue for main numbers
- tweaked various layouts to get everything looking good on all the viewports/print
- Win10 / IE11
- Win10 / Edge17
- macOS / Safari 10.13.6
- macOS / Chrome 69
- macOS / FF 62
- Android 8.1 / Chrome 69
- iOS 11.3 iPad / Safari
- iOS 12.0 iPhone 6 / Safari
- my local Snap Service
Sample PDF from Snap: …
> DSR-42: match print design

- nuxt.config.js
- package-lock.json
- package.json
Installs GTM on production. The Nuxt module claims to detect `NODE_ENV` and avoids tracking non-production environments, but when I run `npm run dev` on my local I still see it.
This at least gets us tracking on the live site and we can somehow expunge my dev noise later on.
> DSR-1: install Google Tag Manager

- components/AppBar.vue
- components/AppFooter.vue
- components/AppHeader.vue
- components/Article.vue
- components/Card.vue
- components/KeyFigures.vue
- components/KeyMessages.vue
- pages/country/_slug.vue
- static/global.css
This finally brings us to something I can call an MVP without wincing. Biggest improvement was the color matching, which now should be pretty close to expected output instead of darker, less saturated colors.
Lots of margins/paddings tweaked, I tried to eliminate left/right whitespace and let the 10mm page margin do the work of providing a border.
Some code re-org happened in the process as I found a convention I was happy with in terms of defining print styles. When the layout differs drastically I defined a block with several rules. When it was just one prop being overridden I opted for nested media blocks using the SCSS syntax.
Snap PDF: [DSR-42-print-r2.pdf](https://github.com/UN-OCHA/reports-site/files/2495489/DSR-42-print-r2.pdf)
> DSR-42: match print design more closely

- pages/country/_slug.vue
Oh yeah. pre-demo deploys because life's too short not to have fun. This one adds page-specific `<title>` based on Contentful data. Seems to work just fine with SSR.
> DSR-40: SitReps use their main title as HTML page title

- components/Article.vue
Further adjustments based on some feedback from 18 Oct demo. Image captions have less horizontal margin and expand to mostly the full-width of the image itself.
> DSR-42: adjust image captions on PDF printout

- _migrations/01-create-keyFinancialsManual.js
- _migrations/README.md
- components/KeyFigures.vue
- components/KeyFinancials.vue
- package-lock.json
- package.json
- pages/country/_slug.vue
PR contains our initial Contentful migration script to deploy the new config, plus all the Vue templates which render the data on the site. Here is a [PDF from my local Snap Service](https://github.com/UN-OCHA/reports-site/files/2529537/DSR-8-FTS-printout.pdf) demonstrating what the FTS URL looks like when printed.
I have locked the validation down very tight on this one. It has to begin with `https://fts.unocha.org` or the validation fails. I don't want people grabbing any old URL and dropping it in there.
I will run the migration locally before merging this so that our staging can continue using the `master` environment in Contentful.
> DSR-8: Key Financials (manual)

- _migrations/04-update-keyMessages.js
- components/AppHeader.vue
- components/KeyMessages.vue
- nuxt.config.js
- pages/country/_slug.vue
- static/global.css
This PR introduces two aspects to integrate with social media:
- New `<meta>` tags that follow both Twitter and Open Graph (FB) protocol. These tags influence the rich snippets generated by sharing a URL on various platforms. We're using `summary_large_image` on Twitter and FB doesn't offer a similar option.
- Links to the sharing tools on Twitter/FB. We're starting out by using the very lightweight "intents" versions instead of loading tweet/like buttons with badges, which require 3rd-party JS.
> DSR-5: Social Integration

- components/Cluster.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- Fixed visual issues on desktop Clusters when only one Figure is present. Swapped out CSS Grid for Flexbox, which then means Clusters can flow from the right side in desktop. At the same time fixed IE11 issues.
- Protect against situations where unpublished Figures are included in a published Cluster. grrr.
Did some thorough browser testing because the CSS adjustments were kind of fundamental to the display of Figures in general:
- Win8.1 - IE11
- Win10 - Edge 17
- macOS - FF
- macOS - Chrome
- macOS - Safari (Mojave)
- iPhone 6 - iOS 11 - Safari
- iPhone X - iOS 12 - Safari
- Nexus 5X - Android 7 - FF
> DSR-55: Cluster fixes

- components/Article.vue
- components/Cluster.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/country/_slug.vue
- static/global.css
This PR converts Articles to use the Rich Text field type instead of the more-permissive Markdown long-text field. I also enforced validation on heading/title/body to avoid situations where an article was malformed.
- **Major victory:** I removed Markdown from the codebase completely since no other component, reducing the JS payload from 418K to 330K  🎉 
- Defends against unpublished Clusters/Article references breaking page builds.
- Renders all existing Rich Text fields using a more appropriate Vue Component Lifecycle event, meaning the content now appears in SSR instead of needing client-side JS. This was an unfound bug so now it's fixed 👍 
I briefly looked into the migration process but decided to skip it since the amount of text fields affected was four. I manually copied the fields …
> DSR-54: Articles with Rich Text

- components/CardActions.vue
- Allows a PNG to download within the visitor's desktop browser. There's no presentation of the graphic within the web browser. It simply downloads and — depending on a person's browser settings — might automatically open in an app (e.g. macOS Preview)
- Provides some minimal UI feedback so the visitor knows something is happening. The button is also disabled, preventing multiple simultaneous requests.
Here's a GIF to demonstrate. The screencapping software mangled the cursor somehow to please refer to this [MDN article about CSS cursors](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) and mouse over the `wait` table row to see what it will look like on your system.
> DSR-39: PNG downloads

- components/AppBar.vue
- components/Article.vue
- components/Card.vue
- components/CardActions.vue
- components/CardFooter.vue
- components/CardHeader.vue
- components/Cluster.vue
- components/Contacts.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- pages/country/_slug.vue
Display Header/Footer on generated PNGs. The components are generated by the website itself which is why my turnaround on this one was a week faster than PDFs ;)
Any component which extends Card now has the optional ability to include the two new components: `<CardHeader>` and `<CardFooter>`. They are hidden by default but spring to life when the class `snap--png` is applied to the document.
Also included was some cleanup to explicitly define proptypes.
> DSR-39: add CardHeader/CardFooter for use with Snaps

- components/Article.vue
- `max-height` increased to 4000px
- transition time increased to accommodate new `max-height`
> DSR-58: use larger max-height on expanded articles

- components/Article.vue
- components/KeyMessages.vue
- static/global.css
I'd previously been outputting description as the alt text for Key Message image but now it uses Contentful's image-title field. We have no control over fields associated with images but at least we're treating them all the same now. 
I took the liberty of adding the ability to caption the image just like Articles
> DSR-61: Key Message alt + caption

- components/Article.vue
By popular demand: read less!
I previously did this the Wrong Way™ by stepping around Vue's component state and cowboying it with classes, hence why there was no <kbd>Read Less</kbd> before.
The state is now managed in Vue, initialized on client-only to avoid problems with SSR. It's also aware of Snap Service, responding to the conditional class by hiding itself and displaying the full article.
> DSR-24: read more and less

- run_node
This is changed because of the latest yarn / npm Nth switchover.
We do want to make sure the first run of a container do generate the static files using the injected env vars, not the fake default ones.
> make sure nuxt runs generate

- components/KeyFinancials.vue
The last thing! :tada:
PR uses the now-required and strictly-validated FTS URL format in Contentful to extract our Plan ID and dynamically select which FTS dataset we're using.
> DSR-65: use FTS Plan ID from Contentful data

- components/Article.vue
Article read-more links were set to an arbitrary min-height that didn't take images. The new code pulls the min-height into the reactive data and uses it as fallback when no image is present and adds a min-growth value for the calculation. I like it much more 🙂
> DSR-71: Articles' read-more takes images into account

- components/KeyMessages.vue
Using `<figure>` as a CSS Grid element was messing up the position of the image caption. This went unnoticed because we only recently started using a Key Message image with a caption. Easy fix!
> DSR-74: reposition KM image caption

- components/Article.vue
Follow-up to #67 — seemed to fix the issue with articles being truncated to near-zero height. I also added a dash of logic to protect against very short images being uploaded. Our current validations don't allow this to occur but it was trivial to add and will come in handy if smaller image dimensions were ever allowed.
> DSR-71: specify image dimensions to aid article height calculations

- components/AppHeader.vue
- components/_Global.vue
- package-lock.json
- package.json
- pages/country/_slug.vue
- pages/index.vue
Mainly an iOS bug as I'd been using `@blur` to accomplish this on desktop. As a bonus I threw in `touchend` support so at least opening the dialog is fast. Unfortunately my quick poking around could not produce the same effect for the clickaway. [Due to reasons](https://www.quirksmode.org/blog/archives/2010/09/click_event_del.html).
> DSR-75: Share dialog should close when clicks fall outside component

- components/AppHeader.vue
CSS fixes for mobile header. Tested in IE11 plus some desktops, iPhone 6 Safari (iOS 12) just barely squeezes in the full title on homepage, Android 8 Chrome has some breathing room. SitRep pages have more space until someone puts a gigantor title in there.
> DSR-78: mobile header

- components/AppHeader.vue
Another fun one. My original implementation did not allow the app to recover from situations where the date wasn't available because the data was not reactive. So the PR accomplishes the following by better adhering to Vue conventions:
* Date is more often printed in subject line
* When the Date is `undefined` we avoid printing it
* Date is now localized according to user settings.
* Email subject is also localized according to user settings.
> DSR-77: avoid printing meaningless info in email subject

- nuxt.config.js
- pages/country/_slug.vue
PR allows `nuxt generate` to create a static HTML for each sitrep
> OPS-4931: create SitRep-specific routes during static site generation

- components/AppHeader.vue
Well here's the first follow-up to #77 
An attribute that I totally had and then deleted at the last second because I forgot it was necessary when reviewing the code before pushing. At least the component simply fails to render so that's actually a plus because it shows nothing instead of a broken component.
> DSR-46: add PDF output to SnapPage

- components/SnapCard.vue
Putting a `Math.min()` on window width with a control value that forces the "medium" grid prevents Key Messages from appearing too tall in the final PNG.
> DSR-79: Key Message Snap PNG renders at proper height

- pages/country/_slug.vue
I know I'm missing something here but this only happens on stage. I never see this on my local and fiddling with devtools to manually simulate a PDF Snap led me to this solution.
Trying `!important` as it's within a `@media print` block, and I find it easier to understand than unsetting/resetting the styles in two or three places.
> DSR-83: Key Figures should. not. have. a. border.

- components/Snap.vue
- package-lock.json
- package.json
Trying this to start out with. There are unfortunately many network sads that require a bit of cheating on local development via `Access-Control` headers, proxies, and the like. But with them in place I got Chrome and Safari working. macOS FF still saw through my tricks so deploying this on stage and seeing what happens.
I'll test stage with the full array of browsers to at least document what works and what doesn't. With that table we can decide how much effort to invest.
> DSR-81: try a library instead of bespoke download code

- components/Snap.vue
- components/SnapCard.vue
- components/SnapPage.vue
Follow-up to #86 
Setting MIME type on the client-side to help iOS through its struggle.
> DSR-81: set MIME type on client-side blob to help iOS

- components/AppHeader.vue
- static/global.css
Ugly bug, little fix.
I made two changes. First, I set `font-display: swap` instead of the very-aggressive `optional` — in reality I think we are seeing way too many page loads without webfonts (especially since they are loaded non-blocking) and that directly affects the screen real estate available for the title. The condensed font allows several extra characters to appear before wrapping kicks in.
Secondly, I moved the buttons to always be out of the way. On mobile they sit next to the Subscribe/Language and on desktop their position is unchanged from before.
> DSR-92: mobile buttons overlap title

- components/KeyFigures.vue
- locales/en.js
- locales/fr.js
App was crashing when Key Figures were not present. I copied over the function from Funding so it outputs a generic ID when there's no data from Contentful.
> DSR-94: properly handle when no Key Figures are present

- pages/index.vue
Just a few fixes to spruce things up:
* SitReps are not bunched up so tight.
* restored the original formatting we were using during the ol' Markdown days
* Added trailing slashes to the URLs in the SitRep list which plays nicer with statically generated URLs
> DSR-53: cosmetic fixes to homepage

- components/Article.vue
- components/_Global.vue
This approach seems to work nicely provided the connection is fast enough. We can set this higher based on some experimentation but in my local testing (which still uses images from Contentful) this was enough to get the height right without revealing the resize when I scroll immediately.
> DSR-71: artificial delay for truncated Article height calc

- components/Article.vue
- pages/country/_slug.vue
Articles now start on page 1 immediately following Key sections. When images are present, their appearance on page 1 is dependent on their dimensions physically fitting the vertical space available below Key sections. When space does not permit, the image will appear on page two, allowing Article text to inhabit all available space on page 1.
> DSR-101: PDF output should be more dense

- components/SnapCard.vue
- components/SnapPage.vue
PR modifies Snaps to send cookies along with the request. It integrates with SitRep's `middleware/i18n.js` which — among other methods — reads cookies to determine what language to use for the UI. End result is localized PNG/PDF downloads!
> DSR-111: send cookies along with PNG/PDF Snap requests

- components/Article.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- package-lock.json
- package.json
While giving @left23 a tour of the codebase, her eagle eyes spotted some inconsistencies in how I'd handled variables in the templates.
- `this` keyword is totally unnecessary in templates. removed.
- some methods were using shorthand and some not. I've resolved to use shorthand.
> No Ticket: template coding standards

- components/KeyFinancials.vue
- pages/country/_slug.vue
For whatever the reason (404, 500, timeout, etc), when we do not receive data from FTS we need to handle it without blowing our site up. This can happen on both the server during static generation, and also on the client as a visitor browses between pages.
Before, when we couldn't get data from FTS we just logged the error to console and did not even gracefully recover in the template. Now, when the data fails to come back we display a message informing the user of the problem.
This should fix navigations, direct page loads, and static generations. In cases where the statically generated site was successful, but a future direct-visit fails to query client-side, we also bail out and maintain the hard-coded response from the static file.
A future optimization would be to stuff the response …
> DSR-86: handle failed calls to FTS

- pages/country/_slug.vue
There was a blunder involved with #109 which led me to believe the site would load the correct language when it would in fact not do that whatsoever. The `npm run dev` command does dynamically-generated SSR but our production does statically-generated SSR with EN as our default language. I did not test the original PR with statically-generated files. 😳 
I have added a client-side check for the user's cookies which switches the language before mounting all the components on SitRep pages. It adds a pretty substantial re-render in to the initial operations to show the page, and will show english until the code gets to checking cookies. However the content of the page will always be in the intended language, and this only affects translated strings running through `$t()` in the Vue …
> DSR-111: do a client-side check for locale cookie

- components/AppFooter.vue
- locales/README.md
- locales/en.js
- locales/fr.js
1. Since this is to display on all pages, the UL is outside the "related links" conditional div.
2. [Translations for the two links and their associated URL](https://github.com/UN-OCHA/reports-site/compare/dsr-113-footer-links?expand=1#diff-009425b4759624e828c30d11c94db76bR15). This might be going too far. The rationale is based on the URLs including the language (eg. https://www.un.org/en/... and https://www.un.org/fr/...)
3. There are [placeholders for the translated links](https://github.com/UN-OCHA/reports-site/compare/dsr-113-footer-links?expand=1#diff-a6c47b7bb79867cbde1d10582942f87bR35) but I did not include proper fr strings. 
@rupl If you see fit, please add [Privacy policy](https://github.com/UN-OCHA/reports-site/compare/dsr-113-footer-links?expand=1#diff-a6c47b7bb79867cbde1d1058 …
> DSR-113 Privacy and copyright footer links

- pages/country/_slug.vue
- static/global.css
There's frequently whitespace under Key Messages due to the user-generated content being an unpredictable height. This PR comments out the last grid option which moved the boxes to the right column, meaning Key Messages now only grows to its natural height instead of depending on the height of the other three smaller modules.
I also reduced the width of the containers in general, from 1200px to 1080px. Hopefully this allows the top area to look nice without too drastically changing the shape of the longer-form articles below.
> DSR-103: adjust layout of Key Stuff

- app.html
- components/Article.vue
- components/FlashUpdate.vue
- components/KeyMessages.vue
- components/_Global.vue
Re-using the Flash Update timestamp code across Articles and Key Messages. Moved most logic into the Global mixin so any future timestamping should go smoothly and with less manual setup.
> DSR-132: show timestamps on cards

- README.md
- nuxt.config.js
- plugins/contentful.js
We want editors to be able to preview their edits, so I'm modifying how we consume our environment variables to ensure that when `CTF_CDA_PREVIEW_TOKEN` is present, it is used as the `accessToken`.
Local testing went as follows:
1. Setup my `.contentful.json` to not have preview token, and `CTF_HOST` set to the default — browsing around the site shows only published content
2. Setup my `.contentful.json` to have `CTF_HOST=preview.contentful.com` and `CTF_CDA_PREVIEW_TOKEN` is present — browsing around displays unpublished edits or even new, unpublished entries.
Let's give this a whirl on stage and see if we can get our preview content!
> OPS-5309: preview environment

- components/Article.vue
- components/CardActions.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/KeyFigures.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- components/SnapCard.vue
We had a request to add unique labels to the PNG download buttons in order to further organize the GTM reports for downloads.
> DSR-120: unique labels for each PNG download

- components/Contacts.vue
Attempt to hide the emails a little bit and at least require Vue to be booted before they are displayed. The `window.__NUXT__` object still holds them in the clear so maybe this change isn't effective, but it's at least removing them from the `mailto:` prefix in the HTML response.
> DSR-129: hide emails in SSR

- components/_Global.vue
- locales/en.js
- locales/fr.js
I realized while doing some other work that the timestamps weren't displaying in French. This PR takes care of it, translating into French to begin with. I re-used the social sharing logic which uses a placeholder to translate the strings (in this case a `#`), then substitutes the placeholder afterward.
> DSR-132: localize timestamps in french

- components/Article.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/Video.vue
- components/_Global.vue
Ensure our RichText fields don't crash when rendering missing or empty fields. This is possible because of unvalidated input being rendered on our new Preview URLs. Since Contentful validation only applies when you hit "Publish" in their UI, the preview environment can get into a state where blank fields are rendered.
I also snuck in a timestamp on the Cluster component. I missed it during #125 and #133
> DSR-134: RichText preview

- components/Article.vue
- layouts/default.vue
Our original image captions were occasionally getting in the way of content when images contained actual information, as opposed to being plain photos. Infographics had legends or other important captioning covered up. On mobile, an especially long caption would exceed the height of an image and overflow upward, an especially awkward visual bug.
We disabled the `screen` styles and opted for `print` on all media, since they don't overlay and just sit below the image.
> DSR-126: more predictable image captions

- components/Article.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyMessages.vue
- components/_Global.vue
- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
After #140 introduced the first responsive image I felt compelled to get all the other components on board. With this PR we can truly encourage the editors to upload the absolute highest quality graphics they have on hand, and our code will now pull an appropriate format/size for the device. Components that we updated:
* Key Messages
* Article
* Flash Update
I used the full picture syntax in order to give browsers a chance to select WebP over JPG when they so desire, in addition to various pixel-density and dimension options. The testing results are in the ticket but to summarize the bandwidth reduction (higher is good):
* Desktop: 50%
* Mobile retina screen: 66%
* Mobile non-retina: 90%
The fallback for all images is currently configured to output what is best for IE11 since it's the …
> DSR-97: Responsive images for all components

- nuxt.config.js
- pages/country/_slug.vue
We have these non-fatal errors during static generation and I'm hoping to get rid of them by switching to our production FTS URL during deploys on all environments. We no longer use the environment-specific baseURL to query FTS.
> OPS-5270: potential workaround for 401s

- components/SnapPage.vue
We're having troubles with HTTP/2 and what has been described as "corrupted content" causing nginx to prematurely close connections, leading to failed PDF downloads on dev/preview environments. Since this will turn into a production bug at some undetermined point when HTTP/2 is rolled out, I'm trying to solve it on our mp03 environments to hedge against the future.
First attempt: just remove a ton of whitespace from our XHRs. Since the PDF failure occurs on all SitReps and all UI languages (only EN/FR at the time of this PR) I have to conclude that I somehow wrote content that is being corrupted.
> DSR-144: remove as much whitspace as possible from PDF Header/Footer

- components/Snap.vue
One more follow-up, even though our HTTP/2 dev environment was fixed by the previous work in this ticket to reduce our encoded whitespace in the querystring params.
This was the advice of the nginx bug and we know it's always zero so why not set it?
> DSR-144: send Content-Length in Snap request

- README.md
- _migrations/11-update-sitrep.js
- _migrations/README.md
- components/AppBar.vue
- components/AppHeader.vue
- components/KeyFinancials.vue
- components/_Global.vue
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
- nuxt.config.js
- pages/404.vue
- pages/_lang/country/_slug.vue
- pages/index.vue
- plugins/i18n.js
- store/index.js
This PR introduces the ability to set a default language on a SitRep. The URL structure is changing to the following:
```
https://reports.unocha.org/LANG/country/SITREP/
https://reports.unocha.org/fr/country/burundi/
https://reports.unocha.org/en/country/ukraine/
```
Otherwise, all existing logic/convention remains the same (client-side language detection, static page URLs, static generation, etc)
> DSR-119: SitRep default language

- components/AppFooter.vue
- layouts/default.vue
People hated making URLs accessible on printouts. We will hide them.
The Snap Service (or any other JS-capable agent) can re-expose them by adding `.snap--print-urls` to `<html>`
> DSR-157: do not display URLs inline on PDFs

- pages/_lang/country/_slug.vue
This loads even more unused data into our static HTML but it at least restores functionality to 2019 FTS appeals.
> DSR-158: display both 2018/2019 FTS appeals

- components/KeyMessages.vue
- components/README.md
- locales/en.js
- locales/fr.js
We're changing labels so that "Key Messages" is now displayed as "Highlights"
> DSR-161: Key Messages => Highlights

- components/Snap.vue
I thought this was helping our previous nginx/http2 issue, but it's apparently not even allowed to be set by the client for security reasons. The browser does it automatically before sending request. TIL.
This PR will remove the following console error from the client:
```
Refused to set unsafe header "Content-Length"
Attempt to set a forbidden header was denied: Content-Length
```
> Client-side Content-Length is forbidden

- components/Article.vue
- package.json
I often use preview mode for local development and let this bug slip through because of it. Articles with an unpublished image present were unceremoniously failing to render on our Training environment (and probably elsewhere but it went unreported).
A few more conditionals and we are now checking not only the presence of an image "Link" in Contentful but also that the linked asset actually has a `fields` object that we can use to render. Contentful has hardcoded validation on Image Assets, meaning the `fields` object cannot exist without a valid URL to their CDN, or the checks for individual properties within would be even more thorough.
> DSR-163: Articles gracefully handle unpublished images

- components/KeyMessages.vue
- layouts/default.vue
I noticed that the Highlights PNG button was causing mobile horizontal overflow. It's annoying because messy thumb swipes turn into messy horizontal or diagonal scrolling. This fix gets us back on track with zero horizontal overflows.
That means scrolling gestures can be performed in a sloppy way, but the results will still be smooth and vertical.
I also noticed that we had a straggler "Key Messages" laying around inside the PNG button for Highlights. Also fixed.
> DSR-168: element-invisible overflow

- components/AppBar.vue
- components/AppHeader.vue
- components/SitrepList.vue
- components/SnapCard.vue
- components/SnapPage.vue
- layouts/default.vue
Nuxt has both statically generated HTML and JS-powered modes. We were displaying all of our JS-powered buttons before the interactivity was possible, leading to occasional confusion in field offices with faltering connections. 
Using this sweet `<no-ssr>` tag to wrap our interactive components, we can avoid showing them until the page has been hydrated by JS.
> DSR-154: avoid rendering JS-powered buttons in static HTML

- components/AppBar.vue
- components/AppHeader.vue
- components/SnapCard.vue
- components/SnapPage.vue
Bunch of bugfixes and UX improvements:
- PDFs had big ugly nav button when I tested on dev. Gone.
- the languages weren't quite lined up in no-JS mode. fixed.
- PDF/PNG buttons lost their in-progress animation when I added the fade-in for `<no-ssr>` — due to the scoping mechanism in Vue, the generic styles in `default.vue` no longer applied generically. Reapplying on each component restored the animation.
> DSR-154: follow-ups

- components/Article.vue
- components/SnapCard.vue
- components/SnapPage.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
The button labels were all frozen to english. This PR cleans them up to be tokenized localizations of whatever is being Snapped (e.g. an Article with label "Emergency Response" is localized in two steps so that the translation output for Arabic ends up being `احفظ الاستجابة للطوارئ كملف PNG`, bidi issues in this comment notwithstanding)
> DSR-169: localize PDF/PNG button labels

- components/Video.vue
Short and sweet. Video thumbnails should never break across the page.
Also it should display a clickable link to the video when printing PDF.
> DSR-186: video content should never be across two pages in PDF

- layouts/default.vue
Follow up to #182  — I didn't change the casing of the references to the files. Ironically, it doesn't matter right now whether we do this or not, but the circle of 🐛 would be complete if we DID turn off the casing rule, because without this PR the URLs would again 404 since the files are now lowercase.
> OPS-5575: lowercase filenames

- components/KeyFinancials.vue
Using a much simpler way of displaying FTS year. Due to the fTS data sometimes specifying dates that are extremely close to year changes (e.g. `2018-01-01T00:00:00Z`) it was rendering the year incorrectly for folks in timezones west of UTC.
> DSR-197: display funding year accurately for all timezones

- components/Article.vue
- components/KeyMessages.vue
- pages/_lang/country/_slug.vue
Hopefully this cuts down on errors during Preview builds in Jenkins. It will also result in fewer 404s on preview environments where there should be some content.
> DSR-198: protect against un-uploaded, unpublished images in Preview env

- components/AppBar.vue
- layouts/error.vue
The 404 page is now living inside the `layouts/error.vue` which means it can't use `asyncData` the way I presumed it could given that the docs say ["treat this just like it were inside `pages/`"](https://nuxtjs.org/guide/views/#error-page)
Anyway, since we can't prerender the content, and I didn't want to move the query inside `SitrepList.vue` because that would break HTML response on the homepage, I just removed the dormant code from the component, along with the text that preceded it, since the words make no sense without the content accompanying them.
People can still use the hamburger when JS is enabled. They can click the logo and return to homepage when JS is disabled. Either way it's better than displaying text that says there is content, but not showing content.
> DSR-173: follow up to 404 page

- package-lock.json
- package.json
- yarn.lock
During an installation @teodorescuserban noticed that versions were mismatched. A few weeks back I froze Nuxt to a specific version to get around a build error we were seeing. A fix has since been released so I've deleted lockfiles and recreated them in order to get us back on the latest version.
> DSR-166: get Nuxt back on latest version and update lockfiles

- components/Contacts.vue
Some offices don't put job titles on their contact blocks. Our site was rendering weird empty spaces when it was omitted. Fixed. (name has also been made mandatory on CTF side)
In the process of checking my work, I found another error related to the rendering of email addresses. Our spam protection was not being removed on client side due to an order of ops bug in the original template code.
> DSR-213 / DSR-214 - changes to Contacts

- components/Article.vue
Luckily this was as easy as I hoped. Moved the DOM ref up to the `<figure>` and the caption height is now part of the calculation.
> DSR-201: include image caption when calculating height of read-more expandos

- _migrations/14-create-visual.js
- components/Visual.vue
- components/_Global.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
- pages/_lang/country/_slug.vue
New content type which can be used to present full-width infographics and other dense imagery. Started as a clone of Interactive with some changes mainly on the Contentful side.
Can be inserted into the main content stream. As part of this work, the stream is now labeled "Content" instead of "Article" — bonus!
I also threw in some pending translations while I had the locales open.
> DSR-212: Visual content-type

- components/Interactive.vue
Caught while locally testing #211 
```
11:06:51  WARN  [vue-i18n] Value of key 'interactive' is not a string!
11:06:51  WARN  [vue-i18n] Cannot translate the value of keypath 'interactive'. Use the value of keypath as default.
```
> DSR-218: fix typo in props for Interactive>CardActions

- _stack/DSRWinstonReporter.js
- nuxt.config.js
- package.json
- pages/_lang/country/_slug.vue
- pages/_lang/index.vue
- yarn.lock
Logs all info to `/var/log/access.log` — currently set to `VERBOSE`, so it will include stuff like webpack info.
I sanitized the tokens that I found in one type of error. There might be more but our API keys are not shared across environments, so we can deploy to dev and see what happens without endangering our prod API token.
> DSR-166: logging

- components/AppHeader.vue
- layouts/default.vue
Fixing two issues:
- SitRep title (the country name) was displaying in wrong font in Arabic
- Right edge of rich-text fields were getting chopped off in at least macOS Chrome (maybe elsewhere TBD pending feedback from folks offering QA)
> DSR-233: Arabic display issues

- pages/_lang/index.vue
I'd forgotten to hardcode the language param when loading the root URL, which lacks the params present on the other language-specific URLs. Additionally, the slug needs to be hardcoded or we'll pull up any old piece of content if new pages are ever added.
> DSR-230: specify English About page on root URL

- _migrations/16-update-keyFinancialsManual.js
- components/KeyFinancials.vue
- components/README.md
- package-lock.json
- package.json
- pages/_lang/country/_slug.vue
We have an office onboarding that lacks an FTS entry. This PR re-enables the manual Funding field and stops requiring FTS URL to be populated. The component now attempts these three scenarios (in this order):
1. **Valid FTS data was supplied**. We show Funding stats, an HRP year, the FTS link, and the progress pie chart.
2. **No FTS URL supplied, but manual figures were entered.** We show the figures, but no HRP year, no link to FTS, nor do we render the pie chart.
3. **No valid FTS URL was entered, and no manual figures were provided.** We show the branded error message.
> DSR-241: re-enable manual Funding field

- components/KeyFinancials.vue
Follow-up to #240 
If the URL is present, but points to a non-existent plan, we should suppress the link. By checking for the Year within the plan, we are certain that valid FTS data was found.
> DSR-241: only display FTS link when valid data was found

- components/Article.vue
- package-lock.json
- package.json
Since FlashUpdate extends Article now, the height calculations are still run even when no FlashUpdate is present. Some additional logic is added in order to avoid running the DOM calculation unless the element is found.
> DSR-247: guard against unrendered FlashUpdate article text

- components/Video.vue
- pages/_lang/country/_slug/index.vue
I had really naive URL parsing for our video embeds. The contentful validation was enough to ensure we always get a real URL, but I never accounted for extra params that might exist at the end. This should fix it, and allow us to ignore all params except the video slug.
> DSR-251: more robust youtube url parsing

- components/Article.vue
- package-lock.json
- package.json
This is a followup to 194e8ba.
The original logic was not strict enough, and an expired Flash Update was still creating JS errors because I'd only guarded one conditional from missing FUs, and both of them tried to access the `clientHeight` of one of the DOM `$refs`.
New function just checks up front for `this.$refs['article']` and stops execution completely when it's found to be `undefined` — the defaults for the component then take over and all is peachy.
> DSR-247: only run computeArticleHeight when we find an Article DOM node

- components/Article.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyMessages.vue
- components/Video.vue
- components/Visual.vue
This is about as great as it gets in the web-perf world! I added two HTML attributes to all of our images within the main content area of a SitRep: Article, FlashUpdate, Interactive, Visuals, Videos.
These tiny HTML attributes direct browsers to defer the loading of images until needed. Lazy-loading with zero JS or other weird trickery!
Currently IE11 and Chrome 76+ support the attributes (I added an older, but stable attribute for IE11). Firefox, Safari, Edge et. al will have support coming.
While testing I also discovered a missing comma in the `<picture>` markup, which should improve image selection logic for devices within the affected media queries.
> DSR-203: lazy-load images using HTML attribute

- components/Article.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyMessages.vue
- components/Visual.vue
We noticed that animated GIFs were getting turned into still images on some browsers. When WebP support is not present, the GIF was getting forced into JPG on our frontend, leading to weirdness.
This PR does less, allowing original media to be displayed in whatever format they were uploaded.
> DSR-265: display original format in picture tags

- components/AppBar.vue
- components/SitrepList.vue
- components/_Global.vue
- pages/_lang/index.vue
The list grew. Time to tame it.
The `SitrepList` component used to serve two different use-cases. One was as a very compact list inside the AppBar, and the other was a more detail-rich list on the homepage. This PR cuts the component down so it's only used inside the AppBar, but the one function that truly needed to be shared between the two contexts was moved out to `_Global.vue`.
The homepage got reconstructed using some of the old markup, but the two components are no longer housed inside one Vue file, meaning future adjustments or redesigns will be far simpler.
The homepage is now grows from being single column on mobile to 3-column grid at its widest, with french-language DRC being used as the calibration for when to break the grid into more columns. IE11 of course has its …
> DSR-263: homepage layout

- _migrations/18-update-sitrep--custom-archive.js
- components/AppHeader.vue
- pages/_lang/country/_slug/index.vue
ROs were requesting the ability to create custom RW archive links, so that multiple countries' worth of products can be shown in their "Archive" link of the SitRep `AppHeader` component.
When `customArchive` field is populated, that URL is used. Otherwise the standard ISO3 is used to construct the normal URL. There is CTF validation to ensure it points only to RW archive page and no other URL can be input.
> DSR-264: Custom RW Archive URL

- components/Article.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyFinancials.vue
- components/KeyMessages.vue
- components/Video.vue
- components/Visual.vue
- components/_Global.vue
- layouts/default.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/ru.js
- locales/uk.js
- pages/_lang/country/_slug/index.vue
- store/index.js
We had two use-cases:
1. Our PNG/PDF artifacts had relative "X days ago" timestamps that made no sense when uploaded to historical archives, social media, or email campaigns. That needed to be fixed.
2. Once the ability to toggle was there, attaching a click handler to each timestamp was trivial, to allow toggling on the page itself if people wish it.
The PR adds the following:
- New units for relative timestamps: week/month/year (translations all pending and set to English for the time being)
- Event listener on timestamps to allow click-to-toggle. Default is still relative timestamp.
- A new property in the Vuex store to control site-wide timestamp formatting.
- A MutationObserver on the `<html>` element that listens for Snap Service to inject one of its classes. When the listener is …
> DSR-182: show absolute/relative timestamps based on context

- components/AppHeader.vue
- pages/_lang/country/_slug/index.vue
- store/index.js
SitReps still show the full set of translations that an office has created.
> DSR-273: limit display of languages on generic pages

- components/FlashUpdate.vue
- components/Snap.vue
- layouts/default.vue
The original ticket had to do with the outline from the anchor, but i nits current form the PDF is always of the entire URL and not a specific anchor. Removing them from the PDF footer seemed best to me.
I also wrapped the outline in a `@media screen` just to be double-sure that it never shows up in a PDF.
> DSR-272: remove anchors from PDFs entirely

- components/Visual.vue
We noticed a 500 error on Yemen's freshly-published SitRep and it boiled down to unpublished images again. I copied over the boilerplate template conditional from Article, but in the process realized we need ELK logs for this, plus we can use the logs to offer remediation steps.
The logs now point directly to the Contentful Entry/Asset in need of fixing.
This applies only to Visuals for now but if it works nicely we can copy it over to other Assets.
> DSR-282: visuals image protection

- pages/_lang/country/_slug/index.vue
We had a SitRep published with no Key Figures. The website had a sad and did not report the problem in our logs. This protects against it, while simultaneously adjusting some Contentful validation to ensure that it won't happen again.
> DSR-286: better validation for SitRep minimum content

- package.json
- pages/_lang/country/_slug/index.vue
Follow-up to allow KeyFigures to display "No data available"
> DSR-286: better error handling for KeyFigures

- components/Article.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyMessages.vue
- components/Visual.vue
During #274 I introduced a regression in the handling of the `sizes` attribute of the picture tags. Commit eb9531f switched to template literals but the attribute wasn't prefixed with a colon, causing the HTML to contain the back-ticks.
> DSR-284: parse sizes attributes of <picture> tags

- pages/_lang/country/_slug/index.vue
Lacking a sitrep slug should show an error instead of treating it as a `SELECT *` type query.
Now instead of a random SitRep with 30-something redundant language choices, you get a 404.
> DSR-279: show 404 at /LANG/country/

- components/Article.vue
- components/FlashUpdate.vue
The FlashUpdate didn't yet sport the 🔗 button allowing people to copy the standalone URL to the clipboard. Now it does.
> DSR-246: FlashUpdate displays CardUrl button like other Cards

- components/CardActions.vue
- components/CardUrl.vue
- locales/ar.js
- locales/en.js
- locales/es.js
- locales/fr.js
- locales/rn.js
- locales/ru.js
- locales/uk.js
There was a need for some UI feedback when copying URLs. This PR adds a little notification that appears above the button once our clipboard library is successful. If the clipboard fails, it logs an error to console, but does not report failure in a visual way to the user.
While testing I noticed a regression that crept in so part of the original work. So this PR also brings all the CardActions buttons back in line with each other. I dropped the old margin-spacing (which implicitly used whitespace nodes to separate them) and went with Flexbox.
Tested in the following:
- Win 7 IE11
- Win 10 Edge 18
- macOS Chrome 78
- macOS Firefox 70
- iOS 11 Safari
- iOS 13 Safari, Chrome
- Samsung Galaxy S8 Android 7 Chrome
- Nexus 5X Android 8 Chrome, Firefox
> DSR-275: user feedback when copying URL

- components/CardAnchor.vue
- components/CardUrl.vue
We do most event tracking in GTM so I split the shared class for CardAnchor/CardUrl into two unique classes to avoid any confusion down the road.
The `href` of the `.btn--card-url` is sufficient to gather data on who is clicking what.
> DSR-271: more specific classes for GTM

- components/AppHeader.vue
- components/CardFooter.vue
- components/FlashUpdate.vue
- components/KeyFinancials.vue
- components/SnapCard.vue
- components/SnapPage.vue
- components/_Global.vue
- locales/rn.js
- pages/_lang/index.vue
- store/index.js
We noticed that moment.js doesn't have support for Kirundi (or a couple other local languages which are on the docket). Long-term we'd love to provide the locales upstream, but in the mean time we've added a `fallback` property to each locale definition so that the official UN-6 language of choice can be substituted when necessary.
> DSR-295: kirundi fallback for JS deps

- _tests/StackRedirects.test.js
Appropriate ticket number!
This PR adds nine E2E tests for our nginx config that controls all of our HTTP redirects. We were testing a couple of these manually and I decided it was better to permanently add it to our testing suite. Easier to test if we ever make further tweaks.
> DSR-302: E2E for our stack redirects

- components/CardUrl.vue
- package.json
During my final cross-browser testing on dev, I noticed on mobile the layout was getting pushed to the side. Initially thinking it an RTL bug, but it turned out to affect pretty much any language on mobile. Desktop wasn't affected.
When copying a CardUrl, the message length can vary since it populates the Card type into the message (e.g. Feature, Visuals and Data, Emergency Response) — the variable length of these messages combined with translations can result in an unpredictable placement. By repositioning the message to not be exactly centered over the button, we can avoid any layout issues on mobile.
> DSR-306: fix layout bug caused by CardUrl feedback element

- _tests/Card.test.js
- _tests/SitRep.test.js
- nuxt.config.js
- pages/_lang/country/_slug/card/_sysid.vue
- pages/_lang/country/_slug/index.vue
Our FB validator complained about the missing App ID. We're re-using the RW ID per Miguel's direction.
> DSR-307: add fb:app_id meta tag + E2E

- pages/_lang/country/_slug/card/_sysid.vue
- pages/_lang/country/_slug/index.vue
* `twitter:image:alt`
* `og:image:width`
* `og:image:height`
* `og:image:type`
Images get scaled down to 1024-wide when they exceed the threshold.
> DSR-297: Twitter/OG image meta tags improved

- pages/_lang/country/_slug/card/_sysid.vue
A really quick win to further customize standalone Card URLs. Whatever Footer customizations are applied to a SitRep, we display those on the Card footers as well now. This includes:
* Custom footer text
* Up to 3x links (typically pointing to unocha.org, HR.info, and reliefweb)
* FB/Twitter accounts for the Office.
Behavior is unchanged if the footer is not customized. We have defaults in place for all languages.
> DSR-308: apply SitRep footer customizations to standalone Cards

- components/_Global.vue
Step 1 for the issue was removing the errors I got while doing local development and switching between branches that don't have the same locale list.
However if we ever managed to add a language in the DB without supporting it in code, this will save us from a fatal error on the homepage.
> DSR-304: guard against missing language when looking up localeName

- components/SnapPage.vue
- pages/_lang/country/_slug/card/_sysid.vue
PDFs of standalone Cards with long titles were looking a bit shaggy. This fixes it up. It may seem like a weird solution, but the Puppeteer PDF Headers are themselves weird and they make us do weird things to work with them. Such is life.
While I was testing I noticed the Cards have an unnecessary `border-bottom` on the PDF. Gone.
> DSR-309: standalone Cards with long titles

- nuxt.config.js
Instead of the gross duplication of logic to create individual sitreps, we now have a factory that is driven off of Contentful data. You can now find an equivalent feed for every SitRep URL that is published on the site:
- `/fr/country/burundi/` => `/feeds/fr/country/burundi.xml`
- `/so/country/somalia/` => `/feeds/so/country/somalia.xml`
...and so forth
> DSR-312: create factory for SitRep-specific feeds

- pages/_lang/country/_slug/flash-update/_sysid.vue
- pages/_lang/country/_slug/index.vue
The workaround was originally in place to freshen content beyond the 5-minute static generation cycle. Over a period of months we first switched to dynamic SSR and then lowered the cache lifetime
from 5 minutes to 1. So the reason to double-fetch data is all but removed nowadays.
Diff is kinda big but I just moved a function from one place to another, not much more.
> DSR-209: remove our hack to call asyncData on page mount

- components/Video.vue
- components/_Global.vue
- package.json
- pages/_lang/country/_slug/card/_sysid.vue
This is a follow-up to the initial social work, which provides much better integration for Videos on social media.
Twitter and FB were implemented, and both networks should render playable video embeds when sharing the respective Card URLs. Other card types are unaffected.
> DSR-289: social integration for Video cards

- pages/_lang/country/_slug/card/_sysid.vue
I made a typo in the FB OG tag for Video cards. Frustratingly, I am unable to do local testing using ngrok to confirm the fix. But I think it will work now.
> DSR-320: set correct value for og:type on Video cards

- components/CardFooter.vue
Our work in DSR-294 means it shows an absolute timestamp at the top of all PDF/PNGs. The 'Date'
label was already confusing and became more so. Fixing the PNG to say 'Downloaded' makes it clear why the dates are different. It also matches what PDFs were already doing.
> DSR-267: CardFooter now says 'Downloaded'

- components/AppHeader.vue
There has occasionally been confusion when looking at multiple environments and we received reports from RW contractors that dev/preview links are being sent to them for publishing.
This indicator should help resolve those issues. It checks the `baseUrl`/`window.location.hostname` and parses for the `reports.*.ahconu.org` pattern. If it finds that pattern, it extracts the subdomain and displays it at the top of the webpage in a sticky header.
> DSR-142: display environment indicator on reports.*.ahconu.org domains

- components/CardActions.vue
- components/CardUrl.vue
- components/FlashUpdate.vue
Our Flash Updates were sending people to the generic CardURL location, but this PR makes it so that the special FlashUpdate URL is used when clicking the 🔗 button.
> DSR-321: Flash Update sets custom CardUrl

- nuxt.config.js
Since the content is listed in the RSS according to the timestamp, we thought it helpful to include prefixes on each content type. I localized them as well.
I also snuck in a caching change to perhaps help with OPS-6156
> DSR-323: RSS prefixes

- components/Article.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/KeyMessages.vue
- components/Video.vue
- components/Visual.vue
- components/_Page.vue
- package.json
- store/index.js
while fantastic for mobile devices, our native lazy-loading broke really long PDFs that contain numerous graphics far below the infamous fold. I've tweaked the logic to allow global overriding and set up our Mutation Observer to flip a switch when it detects that Snap is taking a PDF/PNG.
> DSR-329: don't lazy load images on Snap PDFs/PNGs

- components/AppHeader.vue
New pattern to match AWS site naming conventions.
> OPS-6330: new regex for environment indicators

- .travis.yml
- _tests/unit/AppBar.spec.js
- _ui/dsrSidebarBoolean.html
- components/AppBar.vue
- components/Article.vue
- components/Cluster.vue
- components/FlashUpdate.vue
- components/Interactive.vue
- components/Video.vue
- components/Visual.vue
- pages/_lang/country/_slug/index.vue
For the record, I did this under duress 😉 
There's a new Contentful UI Extension checked into git, which supplies a Boolean on the Sidebar. We're going to use it to allow editors to toggle the behavior of links within their Articles (whether the links open in a new window or not)
Other things I snuck in there:
- I fixed a pretty terrible layout bug that I missed during #364 
- I made it so <kbd>ESC</kbd> closes an open AppBar
> DSR-331: open links new window if someone needs it to be that way

- _tests/unit/AppHeader.spec.js
- _tests/unit/Video.spec.js
- components/AppHeader.vue
- components/Video.vue
We are setting up a custom format for Regional Offices to have country codes. They follow a pattern `/RO[1-9]/` to allow for up to nine regional offices. The number being present will also prevent the possibility of a new ISO3 ever overlapping with these custom codes.
The work in this branch is to prevent the auto-generated Archive link from appearing when these codes are used. Since they're not real ISO3 we can't link to RW using that code.
I also noticed that youtube buttons weren't showing. It's a fairly old regression but we only deployed it two weeks ago. At least it's fixed now.
> DSR-337: regional office code

- components/Video.vue
Follow up to c0593d9, which is itself a follow up to ed884e0.
I seem to have pasted the CSS from a WP project I had laying around, and we don't need to do the same overriding that I mentioned in the unnecessary comment 😳
> DSR-234: fix regression for real this time

- package.json
- yarn.lock
It's baked into our node.js images so we don't need to manage it as a project dependency. See full discussion at OPS-7464.
> DSR-376: remove newrelic from project dependencies

- CONTRIBUTING.md
Standardizing our docs in terms of commits and creating Releases. I had to create CONTRIBUTING.md and even though the other docs are in README, I thought these docs should live in the same location inside the repo as the other three projects.
View them fully-rendered: https://github.com/UN-OCHA/reports-site/blob/DSR-386/CONTRIBUTING.md
> [DSR-386] document standard node.js Release process

- CHANGELOG.md
- package.json
We had to re-do yesterday's deployment (see details in OPS-8282) so to get us on the `standard-version` wagon I'm making a new tag.
> Production 2022-05-04
